- name: Install the latest version of Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove Old nginx files
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a nginx directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

#- name: Download the Frontend Content and Extract File
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes

- name: Download the {{component}} Content and Extract File
  ansible.builtin.unarchive:
    src: http://{{nexus_user}}:{{nexus_pass}}@172.31.3.231:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /usr/share/nginx/html
    remote_src: yes
  vars:
    nexus_user: {{ lookup('aws_ssm', "nexus.user", region='us-east-1' ) }}
    nexus_pass: {{ lookup('aws_ssm', "nexus.pass", region='us-east-1' ) }}

- name: Copy RoboShopConf File to nginx
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start nginx Service
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: restarted

