- name: Disable MySQL 8 Version
  ansible.builtin.shell: dnf module disable mysql -y

- name: Copy Mysql Repo File
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install Mysql
  ansible.buitin.yum:
    name: mysql-community-server
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd:
    name: mysql-community-server
    state: restarted
    enabled: yes

- name: Change Mysql Default Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{root_mysql_password}}
  register: out
  ignore_errors: yes
# based on exit status it ignores the task

- name: Password Status
  ansible.builtin.debug:
    msg: Password Is Already Changed
  when: out.rc == 1
