- name: Setup Server
  ansible.builtin.include_tasks: "server.yml"
  when: prometheus == "server"

- name: Setup Exporter
  ansible.builtin.include_tasks: "exporter.yml"
  when: prometheus == "exporter"