- name: Install GoLang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App PreReq
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: Install GoLang Dependencies
  community.general.npm:
    path: /app
    state: latest

- name: App PreReq
  ansible.builtin.include_tasks: "systemd.yml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load