- name: Copy Mongodb Yum Repo File
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongodb
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

#- name: Load Schema
#  community.mongodb.mongodb_shell:
#    login_host: mongodb-dev.raviteja.online
#    file: "/app/schema/{{component}}.js"
#    idempotent: yes

- name: Load Schema
  ansible.builtin.shell: mongo --ssl --host dev-docdb-cluster.cluster-cmscnppwjzuf.us-east-1.docdb.amazonaws.com:27017 --sslCAFile /app/rds-combined-ca-bundle.pem --username {{ lookup('aws_ssm', "{{env}}.docdb.DB_ADMIN_USER", region='us-east-1' ) }} --password {{ lookup('aws_ssm', "{{env}}.docdb.DB_ADMIN_PASS", region='us-east-1' ) }}
