- name: Configure NodeJS Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App PreReq
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: Install NodeJS Dependencies
  community.general.npm:
    path: /app
    state: latest

- name: Download DocDB CA file
  ansible.builtin.get_url:
    url:  https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    dest: /app/rds-combined-ca-bundle.pem
  when: schema_load

- name: Setting Systemd
  ansible.builtin.include_tasks: "systemd.yml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load